version: "3.7"

services:
  db.postgres:
    image: postgres:13
    container_name: db.postgres
    networks:
      - backend
    environment:
      POSTGRES_DB: zypress_db
      POSTGRES_USER: zypress_user
      POSTGRES_PASSWORD: zypress_pwd
    ports:
      - 5432:5432
    volumes:
      - ./seed:/docker-entrypoint-initdb.d
      - ./data/postgres_db:/var/lib/postgresql/data
networks:
  backend: